import { items } from './items.generated';

export type CatalogItem = (typeof items)[number];

export const itemImages: Record<string, string> = {
  'Adamantin Sisak': '/items/adamantin-sisak.jpeg',
  'Amulet of wisdom': '/items/amulet-of-wisdom.jpeg',
  'Belt of the Hill Giant': '/items/belt-of-the-hill-giant.jpeg',
  'Basic poison': '/items/basic-poison.jpeg',
  'Black Panter Studded Armor': '/items/black-panter-studded-armor.jpeg',
  'Black Wolf Fur': '/items/black-wolf-fur.jpeg',
  'Blinkdagger': '/items/blinkdagger.jpeg',
  'Broom of Flying': '/items/broom-of-flying.jpeg',
  'Boots of Striding and Springing': '/items/boots-of-striding-and-springing.jpeg',
  'Bracers of Defense': '/items/bracers-of-defense.jpeg',
  'Bracer of fire resistance': '/items/bracer-of-fire-resistance.jpeg',
  'Braclet of sleight hands': '/items/braclet-of-sleight-hands.jpeg',
  'Catpaw boots': '/items/catpaw-boots.jpeg',
  'Circlet of Blasting': '/items/circlet-of-blasting.jpeg',
  'Cloak of Invisibility': '/items/cloak-of-invisibility.png',
  'Crystal ball': '/items/crystal-ball.jpeg',
  'Decanter of Endless Water': '/items/decanter-of-endless-water.jpeg',
  'Diadem of arcane knowledge': '/items/diadem-of-arcane-knowledge.jpeg',
  'Displacer’s Deceptive Duster': '/items/displacers-deceptive-duster.jpeg',
  'Dragon rum': '/items/dragon-rum.jpeg',
  'Earrings of charm': '/items/earrings-of-charm.jpeg',
  'Elixir of Acid Resistance': '/items/elixir-of-acid-resistance.jpeg',
  'Elixir of Bear': '/items/elixir-of-bear.jpeg',
  'Elixir of Bloodlust': '/items/elixir-of-bloodlust.jpeg',
  'Elixir of Cloud Giant': '/items/elixir-of-cloud-giant.jpeg',
  'Elixir of Cold Resistance': '/items/elixir-of-cold-resistance.jpeg',
  'Elixir of Fire Resistance': '/items/elixir-of-fire-resistance.jpeg',
  'Elixir of Hill Giant': '/items/elixir-of-hill-giant.jpeg',
  'Elixir of Lightning Resistance': '/items/elixir-of-lightning-resistance.jpeg',
  'Elixir of Lynx': '/items/elixir-of-lynx.jpeg',
  'Elixir of Necrotic Resistance': '/items/elixir-of-necrotic-resistance.jpeg',
  'Elixir of Owl': '/items/elixir-of-owl.jpeg',
  'Elixir of Ox': '/items/elixir-of-ox.jpeg',
  'Elixir of Peacock': '/items/elixir-of-peacock.jpeg',
  'Elixir of Poison Resistance': '/items/elixir-of-poison-resistance.jpeg',
  'Elixir of Psychic Resistance': '/items/elixir-of-psychic-resistance.jpeg',
  'Elixir of Radiant Resistance': '/items/elixir-of-radiant-resistance.jpeg',
  'Elixir of Stag': '/items/elixir-of-stag.jpeg',
  'Flametongue shortsword': '/items/flametongue-shortsword.jpeg',
  'Gauntlet of strong hands': '/items/gauntlet-of-strong-hands.jpeg',
  'Greater healing potion': '/items/greater-healing-potion.jpeg',
  'Handbreaker': '/items/handbreaker.png',
  'Healing potion': '/items/healing-potion.jpeg',
  'Immovable Rod': '/items/immovable-rod.jpeg',
  'Javelin of Thunder Peaks': '/items/javelin-of-thunder-peaks.jpeg',
  'Legbreaker': '/items/legbreaker.jpeg',
  'Lightbringer': '/items/lightbringer.jpeg',
  'Méreg ellenszer': '/items/mereg-ellenszer.jpeg',
  'Mithral Láncing': '/items/mithral-lancing.jpeg',
  'Misztikus Rúnakő': '/items/misztikus-runako.jpeg',
  'Orb of Detect magic': '/items/orb-of-detect-magic.png',
  'Prismatic Psychedelic Peepers': '/items/prismatic-psychedelic-peepers.jpeg',
  'Potion of arcane recovery': '/items/potion-of-arcane-recovery.jpeg',
  'Potion of feather fall': '/items/potion-of-feather-fall.jpeg',
  'Potion of Invisibility': '/items/potion-of-invisibility.jpeg',
  'Potion of Speed': '/items/potion-of-speed.jpeg',
  'Purifying Incense': '/items/purifying-incense.jpeg',
  'Quickly Powder': '/items/quickly-powder.jpeg',
  'Reinforced Leather Coat': '/items/reinforced-leather-coat.jpeg',
  'Ring of Arcane Recovery': '/items/ring-of-arcane-recovery.jpeg',
  'Ring of Brightness': '/items/ring-of-brightness.jpeg',
  'Ring of Remove Curse': '/items/ring-of-remove-curse.jpeg',
  'Ring of Spell Storing': '/items/ring-of-spell-storing.jpeg',
  'Ritual Dagger': '/items/ritual-dagger.png',
  'Scrying Eye Orb': '/items/scrying-eye-orb.jpeg',
  'Shatter shard': '/items/shatter-shard.jpeg',
  'Staff of Healing': '/items/staff-of-healing.jpeg',
  'Staff of Sleep': '/items/staff-of-sleep.jpeg',
  'Strong poison': '/items/strong-poison.jpeg',
  'Sunshine-Singer’s Solar Serenade Sickle': '/items/sunshine-singers-solar-serenade-sickle.jpeg',
  'Cast-Iron Critical Clanger': '/items/the-cast-iron-critical-clanger.jpeg',
  'Tigereye Monocle of Darkvision': '/items/tigereye-monocle-of-darkvision.png',
  'Vestments of the Noble Snow-Leopard': '/items/vestments-of-the-noble-snow-leopard.jpeg',
  'Wand of Ice Knife': '/items/wand-of-ice-knife.jpeg',
  'Wand of Sickeness': '/items/wand-of-sickeness.jpeg',
  'Wand of magic missile': '/items/wand-of-magic-missile.jpeg',
};

export const itemKey = (name: string) => name
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLocaleLowerCase('hu')
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-|-$/g, '');

export const allCatalogItems = items.filter((item) => Boolean(itemImages[item.name]));

