export type Merchant = { slug: string; hu: string; en: string; roleHu: string; roleEn: string; location: string; noteHu: string; noteEn: string; image?: string; inventory?: string[]; inventoryMode?: 'potions' | 'gondeth' };

export const merchants: Merchant[] = [
  { slug:'xizi', hu:'Xizi', en:'Xizi', roleHu:'Arkán nagykereskedő', roleEn:'Arcane wholesaler', location:'Westgate', noteHu:'', noteEn:'', image:'/merchants/xizi.jpeg', inventoryMode:'gondeth', inventory:['Sunshine-Singer’s Solar Serenade Sickle','Cast-Iron Critical Clanger','Prismatic Psychedelic Peepers','Displacer’s Deceptive Duster'] },
  { slug:'syla-zora', hu:'Syla Zora', en:'Syla Zora', roleHu:'Mágiakereskedő és könyvtáros', roleEn:'Magic merchant and librarian', location:'Selgaunt', noteHu:'Mágikus tárgyak vizsgálatával és értékbecslésével is foglalkozik.', noteEn:'Also appraises and identifies magic items.', image:'/merchants/syla-zora.png', inventory:['Misztikus Rúnakő','Orb of Detect magic','Scrying Eye Orb','Ritual Dagger','Crystal ball','Wand of Sickeness','Wand of magic missile','Healing potion','Greater healing potion','Potion of Speed','Potion of Invisibility','Elixir of Fire Resistance','Elixir of Cold Resistance','Elixir of Acid Resistance','Elixir of Lightning Resistance'] },
  { slug:'zelen', hu:'Zelen', en:'Zelen', roleHu:'Mágikustárgy-árus', roleEn:'Magic-item merchant', location:'Sirályszirt', noteHu:'A település egyetlen mágikus tárgyakkal kereskedő árusa.', noteEn:'The settlement’s only merchant dealing in magic items.', image:'/merchants/zelen.jpeg', inventory:['Misztikus Rúnakő','Orb of Detect magic','Wand of Ice Knife','Reinforced Leather Coat','Boots of Striding and Springing','Belt of the Hill Giant','Diadem of arcane knowledge'] },
  { slug:'john-smith', hu:'John Smith', en:'John Smith', roleHu:'Kovács', roleEn:'Blacksmith', location:'Cormyr', noteHu:'Felszereléseket, szakkönyveket és mágikus tárgyakat kínál.', noteEn:'Offers equipment, trade manuals, and magic items.', image:'/merchants/john-smith.png', inventory:['Misztikus Rúnakő','Legbreaker','Gauntlet of strong hands'] },
  { slug:'galak-melegparazs-thuuntok', hu:'Galak „Melegparázs” Thuuntok', en:'Galak “Warm-Ember” Thuuntok', roleHu:'Szakértő kovács', roleEn:'Expert blacksmith', location:'Selgaunt', noteHu:'Kovácsmunkákat, szakkönyveket és uncommon tárgyakat kínál.', noteEn:'Offers smithing work, trade manuals, and uncommon items.', image:'/merchants/galak.png', inventory:['Misztikus Rúnakő','Belt of the Hill Giant','Javelin of Thunder Peaks'] },
  { slug:'dagna-daergel', hu:'Dagna Daergel', en:'Dagna Daergel', roleHu:'Szakértő ékszerkészítő', roleEn:'Expert jeweler', location:'Selgaunt', noteHu:'Mágikus ékszereket készít, azonosít és értékesít.', noteEn:'Crafts, identifies, and sells magical jewelry.', image:'/merchants/dagna-daergel.png', inventory:['Diadem of arcane knowledge','Earrings of charm','Amulet of wisdom'] },
  { slug:'nyuzo-zarathek', hu:'Nyúzó Zarathek', en:'Zarathek the Skinner', roleHu:'Szakértő bőrműves', roleEn:'Expert leatherworker', location:'Selgaunt', noteHu:'Mágikus ruházatokat és különleges páncélokat készít.', noteEn:'Crafts magical garments and unusual armor.', image:'/merchants/nyuzo-zarathek.png', inventory:['Misztikus Rúnakő','Vestments of the Noble Snow-Leopard','Black Wolf Fur','Catpaw boots'] },
  { slug:'robert-flatwater', hu:'Robert Flatwater', en:'Robert Flatwater', roleHu:'Tapasztalt alkimista', roleEn:'Experienced alchemist', location:'', noteHu:'Orvosságokat, főzeteket és alkímiai szakkönyveket kínál.', noteEn:'Offers medicines, potions, and alchemical manuals.', image:'/merchants/robert-flatwater.png', inventoryMode:'potions' },
  { slug:'arnyekfozo-vesryn', hu:'Árnyékfőző Vesryn', en:'Shadowbrewer Vesryn', roleHu:'Szakértő alkimista', roleEn:'Expert alchemist', location:'Selgaunt', noteHu:'Orvosságokat, főzeteket és magasabb szintű szakkönyveket kínál.', noteEn:'Offers medicines, potions, and advanced alchemical manuals.', image:'/merchants/arnyekfozo-vesryn.png', inventoryMode:'potions' },
  { slug:'sara-bowsuntide', hu:'Sara Bowsuntide', en:'Sara Bowsuntide', roleHu:'Műkereskedő és értékbecslő', roleEn:'Art dealer and appraiser', location:'Selgaunt', noteHu:'A Bowsuntide műkereskedés képviselője.', noteEn:'Representative of the Bowsuntide art dealership.', image:'/merchants/sara-bowsuntide.jpeg' },
];

export const merchantBySlug = (slug: string) => merchants.find((merchant) => merchant.slug === slug);
