export type Merchant = { slug: string; hu: string; en: string; roleHu: string; roleEn: string; location: string; noteHu: string; noteEn: string; image?: string };

export const merchants: Merchant[] = [
  { slug:'xizi', hu:'Xizi', en:'Xizi', roleHu:'Arkán nagykereskedő', roleEn:'Arcane wholesaler', location:'Westgate', noteHu:'A Gondeth Mageries eladója. A tárgyakat különleges illúziók segítségével mutatja be.', noteEn:'Proprietor of Gondeth Mageries. Presents items with the help of unusual illusions.', image:'/merchants/xizi.jpeg' },
  { slug:'syla-zora', hu:'Syla Zora', en:'Syla Zora', roleHu:'Mágiakereskedő és könyvtáros', roleEn:'Magic merchant and librarian', location:'Selgaunt', noteHu:'Mágikus tárgyak vizsgálatával és értékbecslésével is foglalkozik.', noteEn:'Also appraises and identifies magic items.' },
  { slug:'felszemu-leon', hu:'Félszemű Leon', en:'One-Eyed Leon', roleHu:'Feketepiaci kereskedő', roleEn:'Black-market merchant', location:'Suzail', noteHu:'Fegyvereket, főzeteket és mágikus portékákat szerez be.', noteEn:'Procures weapons, potions, and magical wares.' },
  { slug:'zelen', hu:'Zelen', en:'Zelen', roleHu:'Mágikustárgy-árus', roleEn:'Magic-item merchant', location:'Sirályszirt', noteHu:'A település egyetlen mágikus tárgyakkal kereskedő árusa.', noteEn:'The settlement’s only merchant dealing in magic items.' },
  { slug:'john-smith', hu:'John Smith', en:'John Smith', roleHu:'Kovács', roleEn:'Blacksmith', location:'Cormyr', noteHu:'Felszereléseket, szakkönyveket és mágikus tárgyakat kínál.', noteEn:'Offers equipment, trade manuals, and magic items.' },
  { slug:'galak-melegparazs-thuuntok', hu:'Galak „Melegparázs” Thuuntok', en:'Galak “Warm-Ember” Thuuntok', roleHu:'Szakértő kovács', roleEn:'Expert blacksmith', location:'Selgaunt', noteHu:'Kovácsmunkákat, szakkönyveket és uncommon tárgyakat kínál.', noteEn:'Offers smithing work, trade manuals, and uncommon items.' },
  { slug:'edmund-koltelm', hu:'Edmund Koltelm', en:'Edmund Koltelm', roleHu:'Kovács', roleEn:'Blacksmith', location:'', noteHu:'A rábízott alapanyaggal hajlamos eltűnni.', noteEn:'Known to disappear with materials entrusted to him.' },
  { slug:'dagna-daergel', hu:'Dagna Daergel', en:'Dagna Daergel', roleHu:'Szakértő ékszerkészítő', roleEn:'Expert jeweler', location:'Selgaunt', noteHu:'Mágikus ékszereket készít, azonosít és értékesít.', noteEn:'Crafts, identifies, and sells magical jewelry.' },
  { slug:'orla-vhalos', hu:'Orla Vhalos', en:'Orla Vhalos', roleHu:'Ékszerész', roleEn:'Jeweler', location:'', noteHu:'Gnóm ékszerész és kézműves.', noteEn:'Gnome jeweler and artisan.' },
  { slug:'nyuzo-zarathek', hu:'Nyúzó Zarathek', en:'Zarathek the Skinner', roleHu:'Szakértő bőrműves', roleEn:'Expert leatherworker', location:'Selgaunt', noteHu:'Mágikus ruházatokat és különleges páncélokat készít.', noteEn:'Crafts magical garments and unusual armor.' },
  { slug:'lae-greystone', hu:'Lae Greystone', en:'Lae Greystone', roleHu:'Bőrműves', roleEn:'Leatherworker', location:'', noteHu:'Törp bőrműves, mágikus alapanyagokkal is dolgozik.', noteEn:'Dwarf leatherworker who also works with magical materials.' },
  { slug:'robert-flatwater', hu:'Robert Flatwater', en:'Robert Flatwater', roleHu:'Tapasztalt alkimista', roleEn:'Experienced alchemist', location:'', noteHu:'Orvosságokat, főzeteket és alkímiai szakkönyveket kínál.', noteEn:'Offers medicines, potions, and alchemical manuals.' },
  { slug:'arnyekfozo-vesryn', hu:'Árnyékfőző Vesryn', en:'Shadowbrewer Vesryn', roleHu:'Szakértő alkimista', roleEn:'Expert alchemist', location:'Selgaunt', noteHu:'Orvosságokat, főzeteket és magasabb szintű szakkönyveket kínál.', noteEn:'Offers medicines, potions, and advanced alchemical manuals.' },
  { slug:'sara-bowsuntide', hu:'Sara Bowsuntide', en:'Sara Bowsuntide', roleHu:'Műkereskedő és értékbecslő', roleEn:'Art dealer and appraiser', location:'Selgaunt', noteHu:'A Bowsuntide műkereskedés képviselője.', noteEn:'Representative of the Bowsuntide art dealership.' },
  { slug:'alpharra-anabravvur', hu:'Alpharra Anabravvur', en:'Alpharra Anabravvur', roleHu:'Hajóépítő műhely vezetője', roleEn:'Shipyard proprietor', location:'Selgaunt', noteHu:'Fényűző luxushajók építésével és értékesítésével foglalkozik.', noteEn:'Builds and sells lavish luxury ships.' },
];

export const merchantBySlug = (slug: string) => merchants.find((merchant) => merchant.slug === slug);
