export type Merchant = { slug: string; hu: string; en: string; roleHu: string; roleEn: string; location: string; noteHu: string; noteEn: string; image?: string; inventory?: string[]; inventoryExclude?: string[]; inventoryMode?: 'potions' | 'gondeth' };

export const merchants: Merchant[] = [
  { slug:'xizi', hu:'Xizi', en:'Xizi', roleHu:'Arkán nagykereskedő', roleEn:'Arcane wholesaler', location:'Westgate', noteHu:'', noteEn:'', image:'/merchants/xizi.jpeg', inventoryMode:'gondeth', inventory:['Sunshine-Singer’s Solar Serenade Sickle','Cast-Iron Critical Clanger','Prismatic Psychedelic Peepers','Displacer’s Deceptive Duster','Ring of Spell Storing','Ring of Remove Curse','Crystal ball','Blinkdagger','Broom of Flying','Flametongue shortsword','Ring of Brightness','Staff of Healing','Trailstone of the Known Path','Boots of Striding and Springing','Wand of Ice Knife','Wand of magic missile'], inventoryExclude:['Elixir of Acid Resistance','Elixir of Bloodlust','Elixir of Cloud Giant','Elixir of Cold Resistance','Elixir of Fire Resistance','Elixir of Lightning Resistance','Elixir of Lynx','Elixir of Owl','Elixir of Peacock'] },
  { slug:'syla-zora', hu:'Syla Zora', en:'Syla Zora', roleHu:'Mágiakereskedő és könyvtáros', roleEn:'Magic merchant and librarian', location:'Selgaunt', noteHu:'Mágikus tárgyak vizsgálatával és értékbecslésével is foglalkozik.', noteEn:'Also appraises and identifies magic items.', image:'/merchants/syla-zora.png', inventory:['Misztikus Rúnakő','Orb of Detect magic','Scrying Eye Orb','Ritual Dagger','Crystal ball','Wand of Sickeness','Wand of Ice Knife','Wand of magic missile','Healing potion','Greater healing potion','Potion of arcane recovery','Potion of Speed','Potion of Invisibility','Elixir of Fire Resistance','Elixir of Cold Resistance','Elixir of Acid Resistance','Elixir of Lightning Resistance','Veil of Agony','Staff of Sleep'] },
  { slug:'zelen', hu:'Zelen', en:'Zelen', roleHu:'Mágikustárgy-árus', roleEn:'Magic-item merchant', location:'Sirályszirt', noteHu:'A település egyetlen mágikus tárgyakkal kereskedő árusa.', noteEn:'The settlement’s only merchant dealing in magic items.', image:'/merchants/zelen.jpeg', inventory:['Misztikus Rúnakő','Wand of Sickeness','Reinforced Leather Coat','Healing potion','Elixir of Bloodlust','Elixir of Lynx','Elixir of Owl','Elixir of Peacock','Handbreaker','Méreg ellenszer','Quickly Powder','Basic poison','Dragon rum','Trailstone of the Known Path','Staff of Sleep','Ritual Dagger','Vestments of the Noble Snow-Leopard','Catpaw boots','Braclet of sleight hands','Scrying Eye Orb','Orb of Detect magic','Earrings of charm','Elixir of Cold Resistance','Purifying Incense','Potion of Invisibility'] },
  { slug:'john-smith', hu:'John Smith', en:'John Smith', roleHu:'Tapasztalt kovács', roleEn:'Experienced blacksmith', location:'Cormyr', noteHu:'Felszereléseket, szakkönyveket és mágikus tárgyakat kínál.', noteEn:'Offers equipment, trade manuals, and magic items.', image:'/merchants/john-smith.png', inventory:['Misztikus Rúnakő'] },
  { slug:'galak-melegparazs-thuuntok', hu:'Galak „Melegparázs” Thuuntok', en:'Galak “Warm-Ember” Thuuntok', roleHu:'Szakértő kovács', roleEn:'Expert blacksmith', location:'Selgaunt', noteHu:'Kovácsmunkákat, szakkönyveket és uncommon tárgyakat kínál.', noteEn:'Offers smithing work, trade manuals, and uncommon items.', image:'/merchants/galak.png', inventory:['Misztikus Rúnakő','Belt of the Hill Giant','Javelin of Thunder Peaks','Bracers of Defense','Adamantin Sisak','Lightbringer','Mithral Láncing','Legbreaker','Gauntlet of strong hands'] },
  { slug:'dagna-daergel', hu:'Dagna Daergel', en:'Dagna Daergel', roleHu:'Szakértő ékszerkészítő', roleEn:'Expert jeweler', location:'Selgaunt', noteHu:'Mágikus ékszereket készít, azonosít és értékesít.', noteEn:'Crafts, identifies, and sells magical jewelry.', image:'/merchants/dagna-daergel.png', inventory:['Amulet of wisdom','Diadem of arcane knowledge','Ring of Arcane Recovery','Circlet of scorching'] },
  { slug:'nyuzo-zarathek', hu:'Nyúzó Zarathek', en:'Zarathek the Skinner', roleHu:'Szakértő bőrműves', roleEn:'Expert leatherworker', location:'Selgaunt', noteHu:'Mágikus ruházatokat és különleges páncélokat készít.', noteEn:'Crafts magical garments and unusual armor.', image:'/merchants/nyuzo-zarathek.png', inventory:['Misztikus Rúnakő','Black Wolf Fur','Black Panter Studded Armor','Cloak of Invisibility','Bracer of fire resistance'] },
  { slug:'robert-flatwater', hu:'Robert Flatwater', en:'Robert Flatwater', roleHu:'Tapasztalt alkimista', roleEn:'Experienced alchemist', location:'', noteHu:'Orvosságokat, főzeteket és alkímiai szakkönyveket kínál.', noteEn:'Offers medicines, potions, and alchemical manuals.', image:'/merchants/robert-flatwater.png', inventoryMode:'potions' },
  { slug:'arnyekfozo-vesryn', hu:'Árnyékfőző Vesryn', en:'Shadowbrewer Vesryn', roleHu:'Szakértő alkimista', roleEn:'Expert alchemist', location:'Selgaunt', noteHu:'Orvosságokat, főzeteket és magasabb szintű szakkönyveket kínál.', noteEn:'Offers medicines, potions, and advanced alchemical manuals.', image:'/merchants/arnyekfozo-vesryn.png', inventoryMode:'potions' },
  { slug:'humber-klupler', hu:'Humber Klupler', en:'Humber Klupler', roleHu:'Drágakőcsiszoló és ékszerkészítő', roleEn:'Gemcutter and jeweler', location:'', noteHu:'', noteEn:'', image:'/merchants/humber-klupler.jpeg', inventory:['Circlet of scorching','Ring of Arcane Recovery','Braclet of sleight hands'] },
  { slug:'noena-daendelos', hu:'Noena Daendelos', en:'Noena Daendelos', roleHu:'Szabó és bőrműves', roleEn:'Tailor and leatherworker', location:'', noteHu:'', noteEn:'', image:'/merchants/noena-daendelos.jpeg', inventory:['Black Panter Studded Armor','Cloak of Invisibility',"Evoker's Robe",'Bracer of fire resistance'] },
  { slug:'sara-bowsuntide', hu:'Sara Bowsuntide', en:'Sara Bowsuntide', roleHu:'Műkereskedő és értékbecslő', roleEn:'Art dealer and appraiser', location:'Selgaunt', noteHu:'A Bowsuntide műkereskedés képviselője.', noteEn:'Representative of the Bowsuntide art dealership.', image:'/merchants/sara-bowsuntide.jpeg', inventory:['Moonflower Diadem','Tears of the Frostmaiden','Lost Dawn'] },
];

export const merchantBySlug = (slug: string) => merchants.find((merchant) => merchant.slug === slug);

export const merchantsSellingItem = (item: { name: string; category: string; price: number | null }) => merchants.filter((merchant) => {
  if (merchant.inventoryExclude?.includes(item.name)) return false;
  if (merchant.inventory?.includes(item.name)) return true;
  if (merchant.inventoryMode === 'potions') return item.category === 'Főzet';
  if (merchant.inventoryMode === 'gondeth') return item.category === 'Főzet' || (item.category === 'Mágikus tárgy' && (item.price ?? Infinity) <= 1000);
  return false;
});
