import type { CatalogItem } from './catalog-data';
import type { Language } from './i18n';

const descriptions: Record<string, [string, string]> = {
  'Adamantin Sisak':['Rendkívül ellenálló sisak, amely oltalmazza viselőjét a váratlan csapásoktól.','An exceptionally resilient helmet that protects its wearer from unexpected blows.'],
  'Amulet of wisdom':['Az amulett tisztább gondolatokat és bölcsebb döntéseket kölcsönöz viselőjének.','The amulet grants its wearer clearer thoughts and wiser judgment.'],
  'Basic poison':['Egyszerű fegyverméreg, amely veszélyesebbé teszi a következő találatot.','A simple weapon poison that makes the next successful strike more dangerous.'],
  'Belt of the Hill Giant':['Az öv egy hegyi óriás erejének töredékével ruházza fel viselőjét.','The belt grants its wearer a fragment of a hill giant’s strength.'],
  'Black Panter Studded Armor':['Könnyű páncél, amely macskaszerű fürgeséget kölcsönöz viselőjének.','Light armor that lends its wearer panther-like agility.'],
  'Black Wolf Fur':['Sötét farkasprém, amely félelmetesebb megjelenést ad viselőjének.','Dark wolf fur that gives its wearer a more intimidating presence.'],
  'Blinkdagger':['Tőr, amely egy szempillantás alatt a célpont mellé röpítheti használóját.','A dagger that can carry its wielder beside the target in the blink of an eye.'],
  'Boots of Striding and Springing':['A csizma hosszabb lépteket és emberfeletti szökkenéseket tesz lehetővé.','These boots enable longer strides and extraordinary leaps.'],
  'Bracer of fire resistance':['A karperec megóvja viselőjét a lángok perzselő erejétől.','The bracer shields its wearer from the searing force of flames.'],
  'Bracers of Defense':['Védelmező karperecek, amelyek páncél nélkül óvják igazán viselőjüket.','Protective bracers that work best when their wearer is otherwise unarmored.'],
  'Braclet of sleight hands':['A karkötő gyorsabbá és ügyesebbé teszi viselője ujjait.','The bracelet makes its wearer’s fingers quicker and more dexterous.'],
  'Broom of Flying':['Elvarázsolt seprű, amely parancsszóra a magasba emelkedik.','An enchanted broom that rises into the air at its rider’s command.'],
  'Cast-Iron Critical Clanger':['Öntöttvas fegyver, amelynek pusztító csapásait fülsüketítő kongás kíséri. Ráadásul rendkívül ízletes steak készül benne.','A cast-iron weapon whose devastating blows ring with a deafening clang.'],
  'Catpaw boots':['Puha csizma, amely hangtalan, macskaszerű lépteket biztosít.','Soft boots that grant quiet, cat-like footsteps.'],
  'Circlet of scorching':['Tüzes diadém, amely perzselő sugarakat képes szabadjára engedni.','A fiery circlet capable of unleashing scorching rays.'],
  'Cloak of Invisibility':['Titokzatos köpeny, amely képes eltüntetni viselőjét a kíváncsi szemek elől.','A mysterious cloak that can hide its wearer from prying eyes.'],
  'Crystal ball':['Kristálygömb, amelyen keresztül távoli helyek és személyek figyelhetők meg.','A crystal ball through which distant places and people may be observed.'],
  'Decanter of Endless Water':['Mágikus kancsó, amelyből soha nem fogy el a tiszta víz.','A magical decanter whose supply of fresh water never runs dry.'],
  'Diadem of arcane knowledge':['A diadém megnyitja viselője elméjét a mágia rejtett összefüggései előtt.','The diadem opens its wearer’s mind to the hidden patterns of magic.'],
  'Displacer’s Deceptive Duster':['Köpeny, amely eltorzítja viselője helyzetét és megtéveszti támadóit.','A coat that distorts its wearer’s position and deceives attackers.'],
  'Dragon rum':['Erős rum, amely rövid időre sárkányszerű leheletet kölcsönöz.','Potent rum that briefly grants a breath reminiscent of a dragon.'],
  'Earrings of charm':['A fülbevalók ellenállhatatlanabbá teszik viselőjük bűvölő jelenlétét.','These earrings make their wearer’s charming presence harder to resist.'],
  'Elixir of Aboleth':['Idegen ízű elixír, amely természetellenesen élessé teszi az elmét.','An alien-tasting elixir that sharpens the mind beyond natural limits.'],
  'Elixir of Acid Resistance':['Az elixír megkeményíti a testet a maró savakkal szemben.','This elixir fortifies the body against corrosive acid.'],
  'Elixir of Bear':['Medveszerű állóképességet és elszántságot kölcsönző elixír.','An elixir that grants bear-like endurance and determination.'],
  'Elixir of Bloodlust':['Harci mámorral tölti el fogyasztóját, de könnyen elhomályosítja ítélőképességét.','Fills the drinker with battle frenzy, but may cloud sound judgment.'],
  'Elixir of Cloud Giant':['A felhőóriások legendás erejével tölti el fogyasztóját.','Imbues the drinker with the legendary strength of cloud giants.'],
  'Elixir of Cold Resistance':['Az elixír ellenállóbbá teszi fogyasztóját a dermesztő hideggel szemben.','This elixir makes the drinker more resistant to bitter cold.'],
  'Elixir of Fire Resistance':['Az elixír ellenállóbbá teszi fogyasztóját a tűz és forróság ellen.','This elixir makes the drinker more resistant to flame and heat.'],
  'Elixir of Hill Giant':['A hegyi óriások nyers erejével tölti el fogyasztóját.','Imbues the drinker with the raw strength of hill giants.'],
  'Elixir of Lightning Resistance':['Az elixír segít elviselni a villámok pusztító erejét.','This elixir helps the drinker withstand the destructive force of lightning.'],
  'Elixir of Lynx':['Hiúzszerű gyorsaságot és ragadozó reflexeket kölcsönöz.','Grants lynx-like speed and predatory reflexes.'],
  'Elixir of Necrotic Resistance':['Az elixír óvja az élő testet a halálenergiák rombolásától.','This elixir protects the living body from the ravages of deathly energy.'],
  'Elixir of Owl':['Bagolyszerű éberséget és kifinomult érzékeket kölcsönöz.','Grants owl-like alertness and finely tuned senses.'],
  'Elixir of Ox':['Ökörszerű teherbírást és rendíthetetlen erőt kölcsönöz.','Grants ox-like stamina and steadfast strength.'],
  'Elixir of Peacock':['Feltűnő kisugárzással és magabiztossággal tölti el fogyasztóját.','Fills the drinker with striking presence and confidence.'],
  'Elixir of Poison Resistance':['Az elixír ellenállóbbá teszi a szervezetet a mérgekkel szemben.','This elixir makes the body more resistant to poisons.'],
  'Elixir of Psychic Resistance':['Az elixír megerősíti az elmét a pszichikus támadásokkal szemben.','This elixir fortifies the mind against psychic assault.'],
  'Elixir of Radiant Resistance':['Az elixír tompítja a vakító isteni energiák erejét.','This elixir tempers the force of searing divine radiance.'],
  'Elixir of Stag':['Szarvasszerű lendületet és biztos mozgást kölcsönöz.','Grants stag-like momentum and sure-footed movement.'],
  'Elixir of Tressym':['A tressym különleges látásával ruházza fel fogyasztóját.','Grants the drinker the unusual sight of a tressym.'],
  'Flametongue shortsword':['Rövidkard, amelynek pengéjét lángok ölelik körül.','A shortsword whose blade can be wreathed in flame on command.'],
  'Gauntlet of strong hands':['A kesztyű határozottabbá és erősebbé teszi viselője fogását.','The gauntlet makes its wearer’s grip firmer and stronger.'],
  'Greater healing potion':['Erőteljes gyógyital, amely súlyosabb sebeket is gyorsan összeforraszt.','A potent healing draught capable of rapidly closing serious wounds.'],
  'Handbreaker':['Buzogány, amelynek csapásai megbénítják az ellenfelet.','A heavy mace whose blows weaken an opponent’s ability to fight back.'],
  'Healing potion':['Gyógyital, amely gyorsan enyhíti a sérüléseket és visszaadja az erőt.','A healing draught that quickly eases wounds and restores strength.'],
  'Immovable Rod':['Mágikus rúd, amely aktiválva rendíthetetlenül rögzül a helyén.','A magical rod that becomes unshakably fixed in place when activated.'],
  'Javelin of Thunder Peaks':['Mágikus dárda, amelyben a Mennydörgő-csúcsok vihara visszhangzik.','A magical javelin echoing with the storms of the Thunder Peaks.'],
  'Legbreaker':['Nehéz fegyver, amelynek csapásai a földre kényszerítik az ellenfelet.','A heavy weapon whose blows can break an opponent’s momentum.'],
  'Lightbringer':['Fénylő harci kalapács, amely sugárzó energiával sújtja ellenfeleit.','A luminous warhammer that strikes its foes with radiant energy.'],
  'Méreg ellenszer':['Keserű ellenméreg, amely megtisztítja a szervezetet a mérgezéstől.','A bitter antidote that purges poison from the body.'],
  'Misztikus Rúnakő':['Egy rúnakő, amely mágikus képességekkel ruházhat fel egy tárgyat.','A rare runestone capable of imbuing an item with magical properties.'],
  'Mithral Láncing':['Pehelykönnyű láncing, amely kiváló védelmet nyújt a pengék ellen.','Feather-light chain armor offering excellent protection from blades.'],
  'Orb of Detect magic':['Mágikus gömb, amely felfedi a környezetében rejtőző varázserőt.','A magical orb that reveals arcane power hidden nearby.'],
  'Potion of arcane recovery':['A főzet felfrissíti a varázshasználó kimerült mágikus erejét.','This potion refreshes a spellcaster’s depleted arcane power.'],
  'Potion of feather fall':['A főzet könnyűvé teszi a testet, és biztonságossá a zuhanást.','This potion lightens the body and makes a fall safe.'],
  'Potion of Invisibility':['A főzet egy időre eltünteti fogyasztóját a szem elől.','This potion hides its drinker from sight for a time.'],
  'Potion of Speed':['A főzet természetfeletti gyorsasággal és lendülettel tölti el fogyasztóját.','This potion fills the drinker with supernatural speed and momentum.'],
  'Prismatic Psychedelic Peepers':['Észvesztő szemüveg, amely megbabonázó illúziókkal ejti rabul a tekintetet.','Iridescent spectacles that captivate onlookers with mesmerizing illusions.'],
  'Purifying Incense':['Tisztító füstölő, amelynek illata eloszlatja az enyhébb átkokat.','Purifying incense whose smoke dispels lesser curses.'],
  'Quickly Powder':['Élénkítő por, amely éberen tartja és felgyorsítja használóját.','An invigorating powder that keeps its user alert and quick-footed.'],
  'Reinforced Leather Coat':['Megerősített bőrkabát, amely tompítja a pengék és nyilak erejét.','A reinforced leather coat that softens the impact of blades and arrows.'],
  'Ring of Arcane Recovery':['A gyűrű segít visszanyerni a varázslás során elvesztett mágikus erőt.','The ring helps restore magical power spent through spellcasting.'],
  'Ring of Brightness':['A gyűrű szelíd fényt áraszt viselője körül.','The ring sheds a gentle light around its wearer.'],
  'Ring of Remove Curse':['A gyűrűben rejlő mágia képes megtörni az átkokat.','The magic held within this ring can break a curse.'],
  'Ring of Spell Storing':['A gyűrű varázslatot őrizhet meg későbbi felhasználásra.','The ring can preserve a spell for later use.'],
  'Ritual Dagger':['Arkán tőr, amely meggyorsítja a vele végzett mágikus szertartásokat.','An arcane dagger that hastens magical rituals performed with it.'],
  'Scrying Eye Orb':['A gömb távolról irányítható szemmé változhat.','The orb can transform into an eye controlled from afar.'],
  'Shatter shard':['Törékeny kristályszilánk, amely becsapódáskor pusztító hanghullámot kelt.','A brittle crystal shard that releases a destructive shockwave on impact.'],
  'Staff of Healing':['Bot, amely gyógyító mágiával támogatja a sebesülteket.','A staff that aids the wounded with restorative magic.'],
  'Staff of Sleep':['Bot, amely mágikus álmot bocsáthat a közelben lévőkre.','A staff capable of casting nearby creatures into magical slumber.'],
  'Strong poison':['Erős fegyverméreg, amely súlyos következményekkel járó sebet okozhat.','A potent weapon poison capable of making a wound far more severe.'],
  'Sunshine-Singer’s Solar Serenade Sickle':['Ragyogó sarló, amely dalra és napfényre ébred fel igazán. Napszemüveg használata javasolt.','A radiant sickle that truly awakens through song and sunlight.'],
  'Tigereye Monocle of Darkvision':['Tigrisszem monokli, amely áthatol a természetes sötétségen.','A tiger-eye monocle that pierces natural darkness.'],
  'Vestments of the Noble Snow-Leopard':['Előkelő öltözék, amely tekintélyt és meggyőző jelenlétet kölcsönöz.','Noble vestments that lend authority and a persuasive presence.'],
  'Wand of Ice Knife':['Fagyos pálca, amely jégből formált lövedéket idéz.','A frost-covered wand that conjures a blade of ice.'],
  'Wand of magic missile':['Pálca, amely tévedhetetlen mágikus lövedékeket bocsát ki.','A wand that releases unerring bolts of magical force.'],
  'Wand of Sickeness':['Baljós pálca, amely betegséget és gyengeséget sugároz áldozatára.','An ominous wand that projects sickness and weakness onto its victim.'],
  "Evoker's Robe":['Varázslóköntös, amely felerősíti a romboló mágiák erejét.','A wizard’s robe that amplifies the power of destructive magic.'],
  'Moonflower Diadem':['Amlaruil Moonflower elveszett diadémja, mely ragyogó fénnyel és védelemmel áldja meg viselőjét.','The lost diadem of Amlaruil Moonflower, blessing its wearer with radiant light and protection.'],
  'Veil of Agony':['Sötét köpeny, amely az okozott fájdalomból táplálja viselője életerejét.','A dark cloak that feeds its wearer’s vitality with the pain they inflict.'],
  'Tears of the Frostmaiden':['Jeges nyaklánc, amelyben a Auril istennő dermesztő haragja szunnyad.','An icy necklace holding the Frostmaiden’s freezing wrath.'],
  'Lost Dawn':['Lathander elveszett nyaklánca, amely a hajnal fényével gyógyítja a sebesülteket.','Lathander’s lost necklace, healing the wounded with the light of dawn.'],
};

export function publicDescription(item: CatalogItem & { originalName?: string }, language: Language) {
  const description = descriptions[item.originalName ?? item.name];
  if (description) return description[language === 'hu' ? 0 : 1];
  if (language === 'hu') return `Különleges ${item.category.toLocaleLowerCase('hu')}, amelynek valódi ereje csak használat közben mutatkozik meg.`;
  return `An unusual ${item.category.toLocaleLowerCase('en')} whose true power reveals itself only in use.`;
}
